// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week4Task4pt2.Infrastructure.Persistence;

#nullable disable

namespace Week4Task4pt2.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251026004910_FixAuthorRelationship")]
    partial class FixAuthorRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Week4Task4pt2.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1828, 9, 9),
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1860, 1, 29),
                            Name = "Anton Chekhov"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1903, 6, 25),
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(1775, 12, 16),
                            Name = "Jane Austen"
                        });
                });

            modelBuilder.Entity("Week4Task4pt2.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            PublishedYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            PublishedYear = 1877,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            PublishedYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            PublishedYear = 1880,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            PublishedYear = 1904,
                            Title = "The Cherry Orchard"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            PublishedYear = 1896,
                            Title = "The Seagull"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            PublishedYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            PublishedYear = 1811,
                            Title = "Sense and Sensibility"
                        });
                });

            modelBuilder.Entity("Week4Task4pt2.Domain.Models.Book", b =>
                {
                    b.HasOne("Week4Task4pt2.Domain.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Week4Task4pt2.Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
